title = "Pienso, luego he sobrevivido"
description = "Un blog sobre política, economía, filosofía y ciencia en el que el criterio de verdad es la supervivencia del sujeto."
baseurl = "https://piensoluegohesobrevivido.es/"
languageCode = "es"
DefaultContentLanguage = "es"
enableRobotsTXT = true

rssLimit = 20        # Only the last 20 posts

[outputs]
  home = ['html', 'rss', 'json']  # Added json for search
  section = ['html', 'rss']
  taxonomy = ['html']
  term = ['html', 'rss']

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  author = "bgjc"

  # toggle LaTeX rendering (see layouts/partials/extend_head.html)
  math = true

  # PaperMod specific features
  #ShowAllPagesInArchive = true
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = false
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = true
  ShowWordCount = false
  ShowRssButtonInSectionTermList = false
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Bloque de presentación en la página principal
  [params.homeInfoParams]
    enabled = true
    Title = "«Solo la supervivencia es necesaria; todo lo demás es contingente»"
    Content = """
Un blog sobre política, economía, filosofía y ciencia en el que el criterio de verdad es la supervivencia del sujeto.
"""

  [[params.socialIcons]]
    name = "twitter"
    url  = "https://twitter.com/HeLuego"

  [[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

  # Cover image settings
  [params.cover]
    hidden = true
    hiddenInList = false
    hiddenInSingle = true

  # Edit post link (optional)
  #[params.editPost]
  #  #URL = "https://github.com/cjgb/datanalytics/tree/master/content"
  #  URL = "https://github.com/cjgb/datanalytics/issues"
  #  Text = "Sugerir cambios"
  #  appendFilePath = false

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
    style = "monokai"

  [markup.goldmark.renderer]
    unsafe = true  # Allow HTML in markdown

# Menu
[[menu.main]]
  identifier = "archives"
  name = "Por fecha"
  url = "/archives/"
  weight = 20

[[menu.main]]
  identifier = "tags"
  name = "Por tema"
  url = "/tags/"
  weight = 30

[[menu.main]]
  identifier = "categories"
  name = "Por categoría"
  url = "/categories/"
  weight = 40

#[[menu.main]]
#  identifier = "search"
#  name = "Buscar"
#  url = "/search/"
#  weight = 99


